name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # Adjust this to match your deployment branch
#    paths:
#    - 'lambda-exp/**'
#    - 'requirements.txt'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Match your Lambda's runtime version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install awscli

    - name: Zip the Lambda function and dependencies
      run: zip -r function.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Adjust to your Lambda function's region

    - name: Deploy Lambda function
      run: aws lambda update-function-code --function-name YOUR_FUNCTION_NAME --zip-file fileb://function.zip
